ci:
  autoupdate_commit_msg: 'chore: update pre-commit hooks'

repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.0.254"
  hooks:
  - id: ruff
    args: ["--fix", "--show-fixes"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
  - id: mypy
    files: ^src/hypernewsviewer/model/
    args: [--show-error-codes]
    additional_dependencies:
    - attrs>=21.3.0
    - cattrs
    - click>=8.1.1
    - rich
    - types-flask
    - types-python-dateutil
    - types-werkzeug

- repo: https://github.com/PyCQA/pylint
  rev: "v2.16.4"
  hooks:
  - id: pylint
    additional_dependencies:
    - attrs
    - cattrs
    - click
    - flask
    - inflection
    - rich

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.2"
  hooks:
    - id: codespell

- repo: local
  hooks:
  - id: beautify
    name: beautify
    language: node
    entry: js-beautify --replace --type=html --end-with-newline
    types_or: [html]
    additional_dependencies: [js-beautify]
