repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
    args: ["--py38-plus"]

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
  - id: mypy
    files: ^src/hypernewsviewer/model/
    args: [--show-error-codes]
    additional_dependencies:
    - rich
    - attrs>=21.3.0
    - cattrs
    - click
    - types-flask
    - types-werkzeug

- repo: https://github.com/pycqa/flake8
  rev: "4.0.1"
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear

- repo: https://github.com/PyCQA/pylint
  rev: "v2.12.2"
  hooks:
  - id: pylint
    additional_dependencies:
    - click
    - rich
    - cattrs
    - attrs
    - flask
    - inflection
