ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.4"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        files: ^src/hypernewsviewer/model/
        args: [--show-error-codes]
        additional_dependencies:
          - attrs>=21.3.0
          - cattrs
          - click>=8.1.1
          - rich
          - types-flask
          - types-python-dateutil
          - types-werkzeug

  - repo: https://github.com/PyCQA/pylint
    rev: "v3.1.0"
    hooks:
      - id: pylint
        additional_dependencies:
          - attrs
          - cattrs
          - click
          - flask
          - inflection
          - rich

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
        args: ["-Lslac", "-w"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, css, scss, javascript, json]
        args: [--prose-wrap=always]

  - repo: local
    hooks:
      - id: beautify
        name: beautify
        language: node
        entry: js-beautify --replace --type=html --end-with-newline
        types_or: [html]
        additional_dependencies: [js-beautify]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.0.4"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/henryiii/check-sdist
    rev: v1.0.0rc2
    hooks:
      - id: check-sdist
        args: [--inject-junk]
        additional_dependencies: [hatchling]

  - repo: https://github.com/pdm-project/pdm
    rev: 2.15.2
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, -Gdeploy]
        language_version: "3.8"
      - id: pdm-lock-check
        language_version: "3.8"
