ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"

repos:
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.272"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.3.0"
    hooks:
      - id: mypy
        files: ^src/hypernewsviewer/model/
        args: [--show-error-codes]
        additional_dependencies:
          - attrs>=21.3.0
          - cattrs
          - click>=8.1.1
          - rich
          - types-flask
          - types-python-dateutil
          - types-werkzeug

  - repo: https://github.com/PyCQA/pylint
    rev: "v3.0.0a6"
    hooks:
      - id: pylint
        additional_dependencies:
          - attrs
          - cattrs
          - click
          - flask
          - inflection
          - rich

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.4"
    hooks:
      - id: codespell
        args: ["-Lslac"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.9-for-vscode"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, css, scss, javascript, json]
        args: [--prose-wrap=always]

  - repo: local
    hooks:
      - id: beautify
        name: beautify
        language: node
        entry: js-beautify --replace --type=html --end-with-newline
        types_or: [html]
        additional_dependencies: [js-beautify]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.11.2"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/henryiii/check-sdist
    rev: v0.1.2
    hooks:
      - id: check-sdist
        args: [--inject-junk]
        additional_dependencies: [hatchling]

  - repo: https://github.com/pdm-project/pdm
    rev: 2.7.2
    hooks:
      - id: pdm-export
        args: [-o, requirements.txt, -Gdeploy]
      - id: pdm-lock-check
