[tool.poetry]
name = "hypernewsviewer"
version = "0.1.0"
description = "A viewer for HyperNews"
authors = ["Henry Schreiner <henryschreineriii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^1.1"
inflection = "^0.5.1"
attrs = "^20.3.0"
click = "^7.1.2"
rich = "^9.8.0"

pytest = { version = ">=6.2", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2"
libsass = "^0.20.1"

[tool.poetry.extras]
test = ["pytest"]

[tool.poetry.scripts]
hyper-model = "hypernewsviewer.model.__main__:main"
hyper-compile = "hypernewsviewer.compile:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
