[tool.poetry]
name = "hypernewsviewer"
version = "0.1.0"
description = "A viewer for HyperNews"
authors = ["Henry Schreiner <henryschreineriii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^2.0"
markupsafe = "^2.0"
inflection = "^0.5.1"
attrs = "^20.3.0"

pytest = { version = ">=6.2", optional = true }
click = { version = "^7.1.2", optional = true }
rich = { version = "^9.8.0", optional = true }
gunicorn = { version = ">=20.1", optional = true }

[tool.poetry.dev-dependencies]
libsass = "^0.20.1"
pytest = "^6.2"
click = "^7.1.2"
rich = "^9.8.0"

[tool.poetry.extras]
test = ["pytest"]
cli = ["click", "rich"]
deploy = ["gunicorn"]

[tool.poetry.scripts]
hyper-model = "hypernewsviewer.model.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.6"
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
module = ["inflection", "hypernewsviewer.filters.*"]
ignore_missing_imports = true
