[project]
name = "hypernewsviewer"
version = "0.1.0"
description = "A viewer for HyperNews"
authors = [
  {name = "Henry Schreiner", email="henryschreineriii@gmail.com"},
]
requires-python = ">=3.6"

dependencies = [
  "flask>=2.0",
  "markupsafe>=2.0",
  "inflection>=0.5.1",
  "attrs>=20.3.0",
]

[project.optional-dependencies]
test = ["pytest>=6.2"]
cli = [
  "click>=8",
  "rich>=9.8.0",
]
deploy = [
  "gunicorn>=20.1"
]

[tool.pdm.dev-dependencies]
dev = [
  "libsass>=0.20.1",
  "pytest>=6.2",
  "click>=8",
  "rich>=9.8.0",
]

[project.scripts]
hyper-model = "hypernewsviewer.model.__main__:main"

[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.6"
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true

[[tool.mypy.overrides]]
module = ["inflection", "hypernewsviewer.filters.*"]
ignore_missing_imports = true
