[tool.poetry]
name = "hypernewsviewer"
version = "0.1.0"
description = ""
authors = ["Henry Schreiner <henryschreineriii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^1.1"
inflection = "^0.5.1"
attrs = "^20.3.0"
click = "^7.1.2"
rich = "^9.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
hn-model= "hypernewsviewer.model:main"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
